# Generated by Django 4.2.11 on 2024-03-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='components_images')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTO', 'Auto'), ('PICKUP', 'Pickup'), ('COMERCIAL', 'Comercial'), ('SUV', 'SUV'), ('CROSSOVER', 'Crossover')], default='AUTO', max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('thumbnail', models.ImageField(blank=True, upload_to='car_thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='car_images')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('componentes', models.ManyToManyField(to='ego.componente')),
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ego.modelo')),
            ],
        ),
    ]
