# Generated by Django 4.2.11 on 2024-03-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='componente',
            name='imagen_url',
            field=models.URLField(default='http://127.0.0.1:8000/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='imagen_url',
            field=models.URLField(default='http://127.0.0.1:8000/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='thumbnail_url',
            field=models.URLField(default='http://127.0.0.1:8000/'),
            preserve_default=False,
        ),
    ]
